/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    'gallery-photos': GalleryPhoto;
    sponsors: Sponsor;
    people: Person;
    announcements: Announcement;
    events: Event;
    'event-rsvps': EventRsvp;
    'event-photos': EventPhoto;
    stories: Story;
    players: Player;
    'player-aliases': PlayerAlias;
    'player-seasons': PlayerSeason;
    'player-sync-runs': PlayerSyncRun;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    events: {
      photos: 'event-photos';
      rsvps: 'event-rsvps';
    };
    players: {
      seasons: 'player-seasons';
      aliases: 'player-aliases';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'gallery-photos': GalleryPhotosSelect<false> | GalleryPhotosSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-rsvps': EventRsvpsSelect<false> | EventRsvpsSelect<true>;
    'event-photos': EventPhotosSelect<false> | EventPhotosSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    'player-aliases': PlayerAliasesSelect<false> | PlayerAliasesSelect<true>;
    'player-seasons': PlayerSeasonsSelect<false> | PlayerSeasonsSelect<true>;
    'player-sync-runs': PlayerSyncRunsSelect<false> | PlayerSyncRunsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    club: Club;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    club: ClubSelect<false> | ClubSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  legacyUrl?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  /**
   * The section of the Documents page this file is listed under.
   */
  category: 'Codes of Conduct' | 'Policies' | 'Child Safety' | 'Game Day' | 'CCCA Directory';
  legacyUrl?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Lower sort numbers show first; the first six appear on the home page. New uploads go to the front.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-photos".
 */
export interface GalleryPhoto {
  id: number;
  caption?: string | null;
  /**
   * Lower numbers show first. Leave empty on upload to put the photo at the front.
   */
  sortOrder?: number | null;
  legacyUrl?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  tier: 'Platinum' | 'Gold' | 'Silver' | 'Bronze' | 'Player';
  /**
   * Optional. Without a logo the sponsor name is shown as text.
   */
  logo?: (number | null) | Media;
  linkUrl?: string | null;
  /**
   * Order within the tier; lower shows first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  /**
   * For example: President, Vice President, Secretary, Treasurer, Child Safety Officer, Junior Coordinator, Senior Captain, Coach.
   */
  role: string;
  /**
   * Which group the person is listed under on /people and the contact page.
   */
  section?: ('leadership' | 'committee' | 'coach') | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Shown square; use the crop tool on the image to frame the face.
   */
  photo?: (number | null) | Media;
  /**
   * Lower numbers show first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  /**
   * Plain text. Leave a blank line between paragraphs. The first line shows in the home page banner.
   */
  body?: string | null;
  /**
   * The newest published announcement shows as a banner on the home page.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  type: 'one_time' | 'recurring';
  title: string;
  description?: string | null;
  location?: string | null;
  /**
   * Shown on the event card and page.
   */
  cover?: (number | null) | Media;
  /**
   * 24-hour, e.g. 18:00
   */
  eventTime?: string | null;
  /**
   * The day of the event.
   */
  eventDate?: string | null;
  /**
   * Which day it runs every week.
   */
  dayOfWeek?: ('0' | '1' | '2' | '3' | '4' | '5' | '6') | null;
  startDate?: string | null;
  endDate?: string | null;
  /**
   * Dinner choices offered on the RSVP form (e.g. Beef, Chicken, Veg). Leave empty for no dinner step.
   */
  mealOptions?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "Buy tickets"
   */
  paymentLinkLabel?: string | null;
  /**
   * A full https:// link, or empty.
   */
  paymentLinkUrl?: string | null;
  photos?: {
    docs?: (number | EventPhoto)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  rsvps?: {
    docs?: (number | EventRsvp)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-photos".
 */
export interface EventPhoto {
  id: number;
  event: number | Event;
  caption?: string | null;
  /**
   * Lower numbers show first. Leave empty to put the photo at the front.
   */
  sortOrder?: number | null;
  status: 'approved' | 'pending';
  /**
   * Who sent it in from the event page (admin context only).
   */
  submitterName?: string | null;
  legacyUrl?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-rsvps".
 */
export interface EventRsvp {
  id: number;
  event: number | Event;
  /**
   * Which session this answer is for (club wall-clock time). Set by the RSVP form.
   */
  occurrenceDate: string;
  name: string;
  email?: string | null;
  note?: string | null;
  response: 'yes' | 'no';
  /**
   * The dinner option chosen when the RSVP was made; empty means no dinner.
   */
  meal?: string | null;
  editToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  title: string;
  /**
   * Set from the title when the story is created; never changes.
   */
  slug?: string | null;
  /**
   * Shown on the history page cards. Leave empty to use the start of the story.
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  /**
   * Shown as "By …". Defaults to the club name for stories written here.
   */
  authorName: string;
  /**
   * Given by the submitter; never published.
   */
  authorEmail?: string | null;
  status: 'pending' | 'published' | 'rejected';
  /**
   * Written in the admin rather than sent in by the public.
   */
  submittedByAdmin?: boolean | null;
  publishedAt?: string | null;
  reviewedAt?: string | null;
  editToken?: string | null;
  viewToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Senior players are synced from PlayHQ every night. Add photos, bios and honours here; they're never overwritten by the sync. Create a player to add someone from before PlayHQ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  firstName: string;
  lastName?: string | null;
  displayName?: string | null;
  /**
   * Set from the name when the player is created; never changes.
   */
  slug?: string | null;
  /**
   * PlayHQ players come from the nightly sync and cannot be deleted.
   */
  source?: ('playhq' | 'manual') | null;
  /**
   * Shown square on the players page; use the crop tool to frame the face.
   */
  photo?: (number | null) | Media;
  /**
   * Plain text. Leave a blank line between paragraphs.
   */
  bio?: string | null;
  /**
   * Years played, e.g. 1978–1992. Shown when the player has no synced seasons.
   */
  manualYears?: string | null;
  /**
   * Leave empty to decide from the synced seasons (played this season or last = active).
   */
  activeOverride?: ('active' | 'past') | null;
  /**
   * Set by the sync: played in the latest two seasons.
   */
  isActiveDerived?: boolean | null;
  /**
   * Hidden players are left off the public site.
   */
  hidden?: boolean | null;
  /**
   * Drag to reorder. Shown on the player page in this order.
   */
  honours?:
    | {
        years?: string | null;
        title: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Written by the PlayHQ sync.
   */
  seasons?: {
    docs?: (number | PlayerSeason)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * PlayHQ names that map to this player. Merging moves them.
   */
  aliases?: {
    docs?: (number | PlayerAlias)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Written by the PlayHQ sync; read only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-seasons".
 */
export interface PlayerSeason {
  id: number;
  player: number | Player;
  seasonName: string;
  /**
   * 0 = newest senior season group.
   */
  seasonOrder: number;
  teamId: string;
  teamName: string;
  gradeName?: string | null;
  games: number;
  batInnings: number;
  batNotOuts: number;
  batRuns: number;
  batHighScore: number;
  batBalls: number;
  batFours: number;
  batSixes: number;
  bowlBalls: number;
  bowlMaidens: number;
  bowlRuns: number;
  bowlWickets: number;
  bowlBestWickets: number;
  bowlBestRuns: number;
  catches: number;
  batHighScoreNotOut?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * PlayHQ name keys (first|last, lower case) and the player each one belongs to. Normally managed by sync and merge.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-aliases".
 */
export interface PlayerAlias {
  id: number;
  nameKey: string;
  player: number | Player;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-sync-runs".
 */
export interface PlayerSyncRun {
  id: number;
  startedAt: string;
  finishedAt?: string | null;
  status?: ('running' | 'ok' | 'error') | null;
  playersCreated?: number | null;
  seasonRows?: number | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'gallery-photos';
        value: number | GalleryPhoto;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-rsvps';
        value: number | EventRsvp;
      } | null)
    | ({
        relationTo: 'event-photos';
        value: number | EventPhoto;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'player-aliases';
        value: number | PlayerAlias;
      } | null)
    | ({
        relationTo: 'player-seasons';
        value: number | PlayerSeason;
      } | null)
    | ({
        relationTo: 'player-sync-runs';
        value: number | PlayerSyncRun;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  legacyUrl?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  legacyUrl?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-photos_select".
 */
export interface GalleryPhotosSelect<T extends boolean = true> {
  caption?: T;
  sortOrder?: T;
  legacyUrl?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  tier?: T;
  logo?: T;
  linkUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  section?: T;
  phone?: T;
  email?: T;
  photo?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  type?: T;
  title?: T;
  description?: T;
  location?: T;
  cover?: T;
  eventTime?: T;
  eventDate?: T;
  dayOfWeek?: T;
  startDate?: T;
  endDate?: T;
  mealOptions?:
    | T
    | {
        label?: T;
        id?: T;
      };
  paymentLinkLabel?: T;
  paymentLinkUrl?: T;
  photos?: T;
  rsvps?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-rsvps_select".
 */
export interface EventRsvpsSelect<T extends boolean = true> {
  event?: T;
  occurrenceDate?: T;
  name?: T;
  email?: T;
  note?: T;
  response?: T;
  meal?: T;
  editToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-photos_select".
 */
export interface EventPhotosSelect<T extends boolean = true> {
  event?: T;
  caption?: T;
  sortOrder?: T;
  status?: T;
  submitterName?: T;
  legacyUrl?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  coverImage?: T;
  authorName?: T;
  authorEmail?: T;
  status?: T;
  submittedByAdmin?: T;
  publishedAt?: T;
  reviewedAt?: T;
  editToken?: T;
  viewToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  displayName?: T;
  slug?: T;
  source?: T;
  photo?: T;
  bio?: T;
  manualYears?: T;
  activeOverride?: T;
  isActiveDerived?: T;
  hidden?: T;
  honours?:
    | T
    | {
        years?: T;
        title?: T;
        id?: T;
      };
  seasons?: T;
  aliases?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-aliases_select".
 */
export interface PlayerAliasesSelect<T extends boolean = true> {
  nameKey?: T;
  player?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-seasons_select".
 */
export interface PlayerSeasonsSelect<T extends boolean = true> {
  player?: T;
  seasonName?: T;
  seasonOrder?: T;
  teamId?: T;
  teamName?: T;
  gradeName?: T;
  games?: T;
  batInnings?: T;
  batNotOuts?: T;
  batRuns?: T;
  batHighScore?: T;
  batBalls?: T;
  batFours?: T;
  batSixes?: T;
  bowlBalls?: T;
  bowlMaidens?: T;
  bowlRuns?: T;
  bowlWickets?: T;
  bowlBestWickets?: T;
  bowlBestRuns?: T;
  catches?: T;
  batHighScoreNotOut?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-sync-runs_select".
 */
export interface PlayerSyncRunsSelect<T extends boolean = true> {
  startedAt?: T;
  finishedAt?: T;
  status?: T;
  playersCreated?: T;
  seasonRows?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "club".
 */
export interface Club {
  id: number;
  name: string;
  /**
   * Short form of the name, e.g. on the admin sign-in screen.
   */
  shortName?: string | null;
  /**
   * Shown under the club name, e.g. the home ground location.
   */
  tagline?: string | null;
  sport?: string | null;
  /**
   * Canonical site URL (no trailing slash). Drives canonical links, the sitemap and structured data.
   */
  siteUrl?: string | null;
  /**
   * Falls back to /assets/branding/logo.png.
   */
  logo?: (number | null) | Media;
  locale?: string | null;
  ogLocale?: string | null;
  email?: string | null;
  sponsorshipSubject?: string | null;
  address?: {
    locality?: string | null;
    region?: string | null;
    regionName?: string | null;
    country?: string | null;
    countryName?: string | null;
  };
  /**
   * Google Maps search for the contact page map.
   */
  mapQuery?: string | null;
  /**
   * An empty URL shows the label as plain text.
   */
  socials?:
    | {
        platform: 'facebook' | 'instagram' | 'x' | 'youtube' | 'tiktok';
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  defaultTitle?: string | null;
  titleSuffix?: string | null;
  defaultDescription?: string | null;
  /**
   * Falls back to /og-image.jpg (1200×630).
   */
  ogImage?: (number | null) | Media;
  ogImageAlt?: string | null;
  pages?: {
    home?: {
      title?: string | null;
      description?: string | null;
    };
    sponsors?: {
      title?: string | null;
      description?: string | null;
    };
    gallery?: {
      title?: string | null;
      description?: string | null;
    };
    documents?: {
      title?: string | null;
      description?: string | null;
    };
    contact?: {
      title?: string | null;
      description?: string | null;
    };
    people?: {
      title?: string | null;
      description?: string | null;
    };
    announcements?: {
      title?: string | null;
      description?: string | null;
    };
    history?: {
      title?: string | null;
      description?: string | null;
    };
    historySubmit?: {
      title?: string | null;
      description?: string | null;
    };
    events?: {
      title?: string | null;
      description?: string | null;
    };
    players?: {
      title?: string | null;
      description?: string | null;
    };
    fixtures?: {
      title?: string | null;
      description?: string | null;
    };
  };
  history?: {
    /**
     * Separate paragraphs with a blank line.
     */
    narrative?: string | null;
    pullQuote?: string | null;
    callout?: {
      eyebrow?: string | null;
      title?: string | null;
      body?: string | null;
    };
  };
  storySubmitIntro?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Sponsors in these tiers scroll across the home page under the hero. Leave empty to hide the carousel.
   */
  sponsorCarouselTiers?: ('Platinum' | 'Gold' | 'Silver' | 'Bronze' | 'Player')[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "club_select".
 */
export interface ClubSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  tagline?: T;
  sport?: T;
  siteUrl?: T;
  logo?: T;
  locale?: T;
  ogLocale?: T;
  email?: T;
  sponsorshipSubject?: T;
  address?:
    | T
    | {
        locality?: T;
        region?: T;
        regionName?: T;
        country?: T;
        countryName?: T;
      };
  mapQuery?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  defaultTitle?: T;
  titleSuffix?: T;
  defaultDescription?: T;
  ogImage?: T;
  ogImageAlt?: T;
  pages?:
    | T
    | {
        home?:
          | T
          | {
              title?: T;
              description?: T;
            };
        sponsors?:
          | T
          | {
              title?: T;
              description?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              description?: T;
            };
        documents?:
          | T
          | {
              title?: T;
              description?: T;
            };
        contact?:
          | T
          | {
              title?: T;
              description?: T;
            };
        people?:
          | T
          | {
              title?: T;
              description?: T;
            };
        announcements?:
          | T
          | {
              title?: T;
              description?: T;
            };
        history?:
          | T
          | {
              title?: T;
              description?: T;
            };
        historySubmit?:
          | T
          | {
              title?: T;
              description?: T;
            };
        events?:
          | T
          | {
              title?: T;
              description?: T;
            };
        players?:
          | T
          | {
              title?: T;
              description?: T;
            };
        fixtures?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  history?:
    | T
    | {
        narrative?: T;
        pullQuote?: T;
        callout?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
            };
      };
  storySubmitIntro?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  sponsorCarouselTiers?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}