/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    'gallery-photos': GalleryPhoto;
    sponsors: Sponsor;
    people: Person;
    announcements: Announcement;
    events: Event;
    'event-rsvps': EventRsvp;
    'event-photos': EventPhoto;
    stories: Story;
    players: Player;
    'player-aliases': PlayerAlias;
    'player-seasons': PlayerSeason;
    'player-sync-runs': PlayerSyncRun;
    'player-sponsors': PlayerSponsor;
    yearbooks: Yearbook;
    pages: Page;
    news: News;
    matches: Match;
    'match-innings': MatchInning;
    'match-appearances': MatchAppearance;
    'match-batting': MatchBatting;
    'match-bowling': MatchBowling;
    'match-fielding': MatchFielding;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    events: {
      photos: 'event-photos';
      rsvps: 'event-rsvps';
    };
    players: {
      committeeRoles: 'people';
      seasons: 'player-seasons';
      aliases: 'player-aliases';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'gallery-photos': GalleryPhotosSelect<false> | GalleryPhotosSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-rsvps': EventRsvpsSelect<false> | EventRsvpsSelect<true>;
    'event-photos': EventPhotosSelect<false> | EventPhotosSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    'player-aliases': PlayerAliasesSelect<false> | PlayerAliasesSelect<true>;
    'player-seasons': PlayerSeasonsSelect<false> | PlayerSeasonsSelect<true>;
    'player-sync-runs': PlayerSyncRunsSelect<false> | PlayerSyncRunsSelect<true>;
    'player-sponsors': PlayerSponsorsSelect<false> | PlayerSponsorsSelect<true>;
    yearbooks: YearbooksSelect<false> | YearbooksSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    'match-innings': MatchInningsSelect<false> | MatchInningsSelect<true>;
    'match-appearances': MatchAppearancesSelect<false> | MatchAppearancesSelect<true>;
    'match-batting': MatchBattingSelect<false> | MatchBattingSelect<true>;
    'match-bowling': MatchBowlingSelect<false> | MatchBowlingSelect<true>;
    'match-fielding': MatchFieldingSelect<false> | MatchFieldingSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    club: Club;
    'club-apparel': ClubApparel;
    'site-settings': SiteSetting;
    theme: Theme;
  };
  globalsSelect: {
    club: ClubSelect<false> | ClubSelect<true>;
    'club-apparel': ClubApparelSelect<false> | ClubApparelSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * People who can sign in to this admin. Editors run the day-to-day website; admins also see the advanced settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown in the greeting, e.g. "Hello, Sam".
   */
  name?: string | null;
  /**
   * Editors see a short, simple menu. Admins also see the Advanced section.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Every picture uploaded to the site. Normally you add pictures from the form that needs them (a sponsor logo, a contact photo, an event cover).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * A few words for people who cannot see the picture, e.g. "Under 12s celebrating the 2024 grand final".
   */
  alt?: string | null;
  legacyUrl?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Forms, policies and newsletters that people can download from the Documents page. PDF files only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * What people will see on the Documents page.
   */
  title: string;
  /**
   * Where on the Documents page this file is listed.
   */
  category: 'Codes of Conduct' | 'Policies' | 'Child Safety' | 'Game Day' | 'CCCA Directory';
  legacyUrl?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Photos on the Gallery page. New photos go to the front, and the first six also show on the home page. Use "Bulk Upload" to add lots at once.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-photos".
 */
export interface GalleryPhoto {
  id: number;
  /**
   * Optional. A few words about the photo.
   */
  caption?: string | null;
  /**
   * Lower numbers show first. Leave empty on upload to put the photo at the front.
   */
  sortOrder?: number | null;
  legacyUrl?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Businesses that support the club. They appear on the Sponsors page, grouped by level.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  /**
   * Higher levels are shown first and bigger. If unsure, leave it as it is.
   */
  tier: 'Platinum' | 'Gold' | 'Silver' | 'Bronze' | 'Player';
  /**
   * Optional. Click the button, then drop the logo picture in. Without a logo the sponsor name is shown as text.
   */
  logo?: (number | null) | Media;
  /**
   * Optional. Where the logo should take people when clicked.
   */
  linkUrl?: string | null;
  /**
   * Leave as 0. A smaller number (such as -1) shows this sponsor before others at the same level.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Committee members, coaches and the people families can contact. They appear on the Contact and People pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  /**
   * For example: President, Vice President, Secretary, Treasurer, Child Safety Officer, Junior Coordinator, Senior Captain, Coach.
   */
  role: string;
  /**
   * Which group of people this person is shown with on the website.
   */
  section?: ('leadership' | 'committee' | 'coach') | null;
  /**
   * Does this person hold another job? Add it here instead of adding them twice. They are then shown under each group with the same picture, phone and email.
   */
  moreRoles?:
    | {
        role: string;
        section?: ('leadership' | 'committee' | 'coach') | null;
        id?: string | null;
      }[]
    | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Optional. Click the button, then drop the picture in. It is shown square, so choose one where the face is in the middle. This is the one place to change their picture: it shows on the home page, Contact, Our People and, if they are also a player, on the Players pages.
   */
  photo?: (number | null) | Media;
  /**
   * Optional. Pick the player if this person also plays. Their picture added here is then used on the Players pages whenever the player has no picture of their own, so you only ever update it in one place.
   */
  player?: (number | null) | Player;
  /**
   * Leave as 0 unless the order matters. Smaller numbers show first (1 is at the top).
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Current players appear here by themselves every night. Add a photo, a short bio and honours to a player. To add someone from years ago, click "Add new".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  firstName: string;
  lastName?: string | null;
  displayName?: string | null;
  /**
   * Set from the name when the player is created; never changes.
   */
  slug?: string | null;
  /**
   * PlayHQ players come in automatically and cannot be deleted.
   */
  source?: ('playhq' | 'manual') | null;
  /**
   * Optional. Click the button, then drop the picture in. It is shown square, so choose one where the face is in the middle. If this player is also under Committee & contacts, the picture on that entry always wins, so change it there. This one is only used when the player has no entry there.
   */
  photo?: (number | null) | Media;
  /**
   * Shown if someone under Committee & contacts is linked to this player. To change their picture, edit it there.
   */
  committeeRoles?: {
    docs?: (number | Person)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Leave a blank line between paragraphs.
   */
  bio?: string | null;
  /**
   * For example 1978–1992. Shown when the player has no seasons recorded automatically.
   */
  manualYears?: string | null;
  /**
   * Leave empty and the site decides (played this season or last = current player).
   */
  activeOverride?: ('active' | 'past') | null;
  /**
   * Set by the sync: played in the latest two seasons.
   */
  isActiveDerived?: boolean | null;
  /**
   * Tick to keep this player off the public website.
   */
  hidden?: boolean | null;
  /**
   * Awards and roles, e.g. "Club champion". Drag to change the order.
   */
  honours?:
    | {
        years?: string | null;
        title: string;
        id?: string | null;
      }[]
    | null;
  baselineGames?: number | null;
  baselineRuns?: number | null;
  baselineWickets?: number | null;
  baselineCatches?: number | null;
  /**
   * Written by the PlayHQ sync.
   */
  seasons?: {
    docs?: (number | PlayerSeason)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * PlayHQ names that map to this player. Merging moves them.
   */
  aliases?: {
    docs?: (number | PlayerAlias)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Written by the PlayHQ sync; read only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-seasons".
 */
export interface PlayerSeason {
  id: number;
  player: number | Player;
  seasonName: string;
  /**
   * 0 = newest senior season group.
   */
  seasonOrder: number;
  teamId: string;
  teamName: string;
  gradeName?: string | null;
  games: number;
  batInnings: number;
  batNotOuts: number;
  batRuns: number;
  batHighScore: number;
  batBalls: number;
  batFours: number;
  batSixes: number;
  batRunsUnballed: number;
  bowlBalls: number;
  bowlMaidens: number;
  bowlRuns: number;
  bowlWickets: number;
  bowlBestWickets: number;
  bowlBestRuns: number;
  catches: number;
  batHighScoreNotOut?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * PlayHQ name keys (first|last, lower case) and the player each one belongs to. Normally managed by sync and merge.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-aliases".
 */
export interface PlayerAlias {
  id: number;
  nameKey: string;
  player: number | Player;
  updatedAt: string;
  createdAt: string;
}
/**
 * News for members. The newest one that is switched on shows as a banner at the top of the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  /**
   * Leave a blank line between paragraphs. The first line shows in the banner on the home page.
   */
  body?: string | null;
  /**
   * Nothing shows on the website until this is switched on. Switch it off later to take the announcement down without deleting it.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Dinners, working bees and presentation days. People can RSVP from the event page on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  type: 'one_time' | 'recurring';
  title: string;
  /**
   * The day of the event.
   */
  eventDate?: string | null;
  dayOfWeek?: ('0' | '1' | '2' | '3' | '4' | '5' | '6') | null;
  startDate?: string | null;
  endDate?: string | null;
  /**
   * Type the time using the 24-hour clock, for example 18:00 for 6pm.
   */
  eventTime?: string | null;
  location?: string | null;
  /**
   * A few lines for people deciding whether to come.
   */
  description?: string | null;
  /**
   * Shown on the event card and page. Click the button, then drop the picture in.
   */
  cover?: (number | null) | Media;
  /**
   * The meals people can pick when they RSVP (e.g. Beef, Chicken, Veg). Leave empty if there is no dinner.
   */
  mealOptions?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  paymentLinkLabel?: string | null;
  /**
   * Where people pay, starting with https://. Leave empty if there is nothing to pay.
   */
  paymentLinkUrl?: string | null;
  photos?: {
    docs?: (number | EventPhoto)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  rsvps?: {
    docs?: (number | EventRsvp)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-photos".
 */
export interface EventPhoto {
  id: number;
  event: number | Event;
  /**
   * Optional. A few words about the photo.
   */
  caption?: string | null;
  /**
   * Lower numbers show first. Leave empty to put the photo at the front.
   */
  sortOrder?: number | null;
  /**
   * Only approved photos show on the event page.
   */
  status: 'approved' | 'pending';
  /**
   * Who sent it in from the event page. Never shown on the website.
   */
  submitterName?: string | null;
  legacyUrl?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-rsvps".
 */
export interface EventRsvp {
  id: number;
  event: number | Event;
  /**
   * Which session this answer is for (club wall-clock time). Set by the RSVP form.
   */
  occurrenceDate: string;
  name: string;
  email?: string | null;
  note?: string | null;
  response: 'yes' | 'no';
  /**
   * The dinner option chosen when the RSVP was made; empty means no dinner.
   */
  meal?: string | null;
  editToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Memories and stories about the club. Members can send them in from the website; they wait here for you to approve.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  title: string;
  /**
   * Set from the title when the story is created; never changes.
   */
  slug?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Click the button, then drop the picture in.
   */
  coverImage?: (number | null) | Media;
  /**
   * Shown as "By …". Type your name, or the club name.
   */
  authorName: string;
  /**
   * Shown on the story card. Leave empty and the start of the story is used.
   */
  excerpt?: string | null;
  /**
   * Given by the person who sent it in. Never shown on the website.
   */
  authorEmail?: string | null;
  /**
   * Use the Approve button at the top, or choose here.
   */
  status: 'pending' | 'published' | 'rejected';
  /**
   * Written in the admin rather than sent in by the public.
   */
  submittedByAdmin?: boolean | null;
  publishedAt?: string | null;
  reviewedAt?: string | null;
  editToken?: string | null;
  viewToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-sync-runs".
 */
export interface PlayerSyncRun {
  id: number;
  startedAt: string;
  finishedAt?: string | null;
  status?: ('running' | 'ok' | 'error') | null;
  playersCreated?: number | null;
  seasonRows?: number | null;
  /**
   * Matches created or changed in the per-match store this run.
   */
  matchesUpserted?: number | null;
  /**
   * Games not stored (junior, club against club, not final).
   */
  matchesSkipped?: number | null;
  /**
   * Players whose per-match totals disagree with their season totals.
   */
  matchMismatches?: number | null;
  /**
   * Games the per-match store failed to write (the season sync still succeeded).
   */
  matchError?: number | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A business that sponsors a particular player. They are shown on the Players page and on that player’s own page. Add the business under Sponsors first (level "Player"), then link it here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-sponsors".
 */
export interface PlayerSponsor {
  id: number;
  /**
   * The player being sponsored. Their picture and name are shown automatically.
   */
  player: number | Player;
  /**
   * The business. Its logo and website come from the Sponsors list, so change those there.
   */
  sponsor: number | Sponsor;
  season?: string | null;
  /**
   * A line or two, up to 280 characters. For example "Proudly backing Sam since 2019".
   */
  message?: string | null;
  /**
   * Tick to show this one at the front of the Player sponsors band.
   */
  featured?: boolean | null;
  /**
   * Leave as 0. A smaller number shows earlier.
   */
  sortOrder?: number | null;
  /**
   * Switch off to hide this sponsorship without deleting it.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One page per season, with your messages and photos beside the stats worked out automatically. Do not upload unreleased photos until you publish: files are reachable by direct link even while the yearbook is a draft.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "yearbooks".
 */
export interface Yearbook {
  id: number;
  /**
   * For example "2025/26 Yearbook".
   */
  title: string;
  /**
   * The season this yearbook covers, written the way it appears on the Fixtures page, for example "Summer 2025/26". The stats and results fill in by themselves.
   */
  seasonName: string;
  /**
   * Set from the season when the yearbook is created; never changes.
   */
  slug?: string | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  cover?: (number | null) | Media;
  /**
   * Optional headline, for example "A Grade premiers".
   */
  premiership?: string | null;
  /**
   * Leave a blank line between paragraphs.
   */
  presidentMessage?: string | null;
  /**
   * Leave a blank line between paragraphs.
   */
  coachMessage?: string | null;
  /**
   * Leave a blank line between paragraphs.
   */
  sponsorMessage?: string | null;
  photos?: (number | GalleryPhoto)[] | null;
  featuredSponsors?: (number | Sponsor)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Information pages such as About the club or Join us. Add text, pictures and buttons, then choose where the link goes in the menu. For dated news use News; for short banners use Announcements.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * The page address, /info/<this>. Set from the title when the page is created. Changing it breaks links to the old address.
   */
  slug?: string | null;
  /**
   * Keep it as Draft while you work. Use the Preview button to see it first.
   */
  status: 'draft' | 'published';
  /**
   * Filled in the first time you publish.
   */
  publishedAt?: string | null;
  /**
   * A draft page never shows in the menu.
   */
  showInNavigation: 'none' | 'clubhouse' | 'primary' | 'footer';
  /**
   * A shorter name for the menu. Leave empty to use the page title.
   */
  navLabel?: string | null;
  /**
   * Smaller numbers come first. Leave as it is to go last.
   */
  navOrder?: number | null;
  /**
   * Add text, pictures and buttons, and drag them into the order you want.
   */
  content?:
    | (
        | {
            richText: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            /**
             * Click the button, then drop the picture in.
             */
            image?: (number | null) | Media;
            /**
             * A few words for people who cannot see it, for example "Under 12s with the premiership cup". Filled in from the picture’s own description when it has one.
             */
            alt: string;
            caption?: string | null;
            width: 'narrow' | 'wide' | 'full';
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            label: string;
            /**
             * A page on this site such as /contact, or a full web address starting with https://.
             */
            url: string;
            style: 'primary' | 'outline';
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  /**
   * Up to 60 characters. Leave empty to use the page title.
   */
  seoTitle?: string | null;
  /**
   * Up to 160 characters. Leave empty to use the start of the first text block.
   */
  seoDescription?: string | null;
  /**
   * Shown when the page is shared on Facebook and similar. Leave empty to use the club picture.
   */
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Dated club news with a picture, such as a result, a signing or a thank-you. For a short banner on the home page use Announcements; for the club’s long-lived history use Club history stories.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * The post address, /news/<this>. Set from the headline when the post is created.
   */
  slug?: string | null;
  /**
   * Keep it as Draft while you work. Use the Preview button to see it first.
   */
  status: 'draft' | 'published';
  /**
   * Filled in with now when you publish. Pick a later date and time to schedule the post: it appears on the website by itself (it can take up to five minutes after that time).
   */
  publishedAt?: string | null;
  /**
   * Shown at the top of the post and on the news list. Click the button, then drop the picture in.
   */
  cover?: (number | null) | Media;
  /**
   * Up to 280 characters, shown on the news list. Leave empty and the start of the post is used.
   */
  excerpt?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Shown as "By …". Leave empty to credit the club.
   */
  author?: string | null;
  /**
   * Up to 60 characters. Leave empty to use the headline.
   */
  seoTitle?: string | null;
  /**
   * Up to 160 characters. Leave empty to use the summary.
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One row per finished senior game, written by the PlayHQ sync. Read only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: number;
  gameId: string;
  status?: string | null;
  type?: string | null;
  seasonName?: string | null;
  seasonStartYear?: number | null;
  competitionName?: string | null;
  gradeId?: string | null;
  gradeName?: string | null;
  roundName?: string | null;
  roundAbbr?: string | null;
  isFinalRound?: boolean | null;
  startsAt?: string | null;
  localDate?: string | null;
  days?: number | null;
  venueName?: string | null;
  venueSuburb?: string | null;
  clubTeamId?: string | null;
  clubTeamName?: string | null;
  opponentTeamId?: string | null;
  opponentName?: string | null;
  opponentOrgId?: string | null;
  opponentOrgName?: string | null;
  isHome?: boolean | null;
  tossWinnerTeamId?: string | null;
  tossChoice?: ('bat' | 'bowl') | null;
  clubWonToss?: boolean | null;
  clubOutcome?: string | null;
  opponentOutcome?: string | null;
  result?: ('won' | 'lost' | 'draw' | 'tie' | 'no_result' | 'abandoned') | null;
  byForfeit?: boolean | null;
  onFirstInnings?: boolean | null;
  playhqUpdatedAt?: string | null;
  sourceHash?: string | null;
  syncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Innings totals for each stored match. Written by the PlayHQ sync. Read only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match-innings".
 */
export interface MatchInning {
  id: number;
  match: number | Match;
  sequenceNo: number;
  periodName?: string | null;
  battingTeamId?: string | null;
  bowlingTeamId?: string | null;
  isClubBatting?: boolean | null;
  periodStatus?: string | null;
  played?: boolean | null;
  declared?: boolean | null;
  allOut?: boolean | null;
  totalRuns?: number | null;
  totalWickets?: number | null;
  totalBalls?: number | null;
  extrasTotal?: number | null;
  wides?: number | null;
  noBalls?: number | null;
  byes?: number | null;
  legByes?: number | null;
  penalty?: number | null;
  hasFallOfWickets?: boolean | null;
  hasBowlingData?: boolean | null;
  hasBallData?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Who played in each stored match. Written by the PlayHQ sync. Read only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match-appearances".
 */
export interface MatchAppearance {
  id: number;
  match: number | Match;
  appearanceId: string;
  teamId?: string | null;
  isClubSide?: boolean | null;
  player?: (number | null) | Player;
  nameKey?: string | null;
  displayName?: string | null;
  captainRole?: string | null;
  isFillIn?: boolean | null;
  isRegisteredPlayer?: boolean | null;
  playerNumber?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Batting lines for each stored match. Written by the PlayHQ sync. Read only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match-batting".
 */
export interface MatchBatting {
  id: number;
  innings: number | MatchInning;
  match: number | Match;
  appearanceId: string;
  position?: number | null;
  battingStatus?: ('out' | 'not_out' | 'did_not_bat' | 'unknown') | null;
  runs?: number | null;
  balls?: number | null;
  fours?: number | null;
  sixes?: number | null;
  dismissalType?:
    | (
        | 'bowled'
        | 'caught'
        | 'caught_and_bowled'
        | 'lbw'
        | 'stumped'
        | 'run_out'
        | 'hit_wicket'
        | 'retired_hurt'
        | 'retired'
        | 'retired_out'
        | 'other'
      )
    | null;
  bowlerAppearanceId?: string | null;
  fielderAppearanceId?: string | null;
  fowWicket?: number | null;
  fowRuns?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bowling figures for each stored match. Written by the PlayHQ sync. Read only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match-bowling".
 */
export interface MatchBowling {
  id: number;
  innings: number | MatchInning;
  match: number | Match;
  appearanceId: string;
  order?: number | null;
  balls?: number | null;
  maidens?: number | null;
  runs?: number | null;
  wickets?: number | null;
  wides?: number | null;
  noBalls?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Fielding statistics for each stored match. Written by the PlayHQ sync. Read only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match-fielding".
 */
export interface MatchFielding {
  id: number;
  innings: number | MatchInning;
  match: number | Match;
  appearanceId: string;
  catches?: number | null;
  keeperCatches?: number | null;
  stumpings?: number | null;
  runOutsAssisted?: number | null;
  runOutsUnassisted?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'gallery-photos';
        value: number | GalleryPhoto;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-rsvps';
        value: number | EventRsvp;
      } | null)
    | ({
        relationTo: 'event-photos';
        value: number | EventPhoto;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'player-aliases';
        value: number | PlayerAlias;
      } | null)
    | ({
        relationTo: 'player-seasons';
        value: number | PlayerSeason;
      } | null)
    | ({
        relationTo: 'player-sync-runs';
        value: number | PlayerSyncRun;
      } | null)
    | ({
        relationTo: 'player-sponsors';
        value: number | PlayerSponsor;
      } | null)
    | ({
        relationTo: 'yearbooks';
        value: number | Yearbook;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'matches';
        value: number | Match;
      } | null)
    | ({
        relationTo: 'match-innings';
        value: number | MatchInning;
      } | null)
    | ({
        relationTo: 'match-appearances';
        value: number | MatchAppearance;
      } | null)
    | ({
        relationTo: 'match-batting';
        value: number | MatchBatting;
      } | null)
    | ({
        relationTo: 'match-bowling';
        value: number | MatchBowling;
      } | null)
    | ({
        relationTo: 'match-fielding';
        value: number | MatchFielding;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  legacyUrl?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  legacyUrl?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-photos_select".
 */
export interface GalleryPhotosSelect<T extends boolean = true> {
  caption?: T;
  sortOrder?: T;
  legacyUrl?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  tier?: T;
  logo?: T;
  linkUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  section?: T;
  moreRoles?:
    | T
    | {
        role?: T;
        section?: T;
        id?: T;
      };
  phone?: T;
  email?: T;
  photo?: T;
  player?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  type?: T;
  title?: T;
  eventDate?: T;
  dayOfWeek?: T;
  startDate?: T;
  endDate?: T;
  eventTime?: T;
  location?: T;
  description?: T;
  cover?: T;
  mealOptions?:
    | T
    | {
        label?: T;
        id?: T;
      };
  paymentLinkLabel?: T;
  paymentLinkUrl?: T;
  photos?: T;
  rsvps?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-rsvps_select".
 */
export interface EventRsvpsSelect<T extends boolean = true> {
  event?: T;
  occurrenceDate?: T;
  name?: T;
  email?: T;
  note?: T;
  response?: T;
  meal?: T;
  editToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-photos_select".
 */
export interface EventPhotosSelect<T extends boolean = true> {
  event?: T;
  caption?: T;
  sortOrder?: T;
  status?: T;
  submitterName?: T;
  legacyUrl?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  coverImage?: T;
  authorName?: T;
  excerpt?: T;
  authorEmail?: T;
  status?: T;
  submittedByAdmin?: T;
  publishedAt?: T;
  reviewedAt?: T;
  editToken?: T;
  viewToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  displayName?: T;
  slug?: T;
  source?: T;
  photo?: T;
  committeeRoles?: T;
  bio?: T;
  manualYears?: T;
  activeOverride?: T;
  isActiveDerived?: T;
  hidden?: T;
  honours?:
    | T
    | {
        years?: T;
        title?: T;
        id?: T;
      };
  baselineGames?: T;
  baselineRuns?: T;
  baselineWickets?: T;
  baselineCatches?: T;
  seasons?: T;
  aliases?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-aliases_select".
 */
export interface PlayerAliasesSelect<T extends boolean = true> {
  nameKey?: T;
  player?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-seasons_select".
 */
export interface PlayerSeasonsSelect<T extends boolean = true> {
  player?: T;
  seasonName?: T;
  seasonOrder?: T;
  teamId?: T;
  teamName?: T;
  gradeName?: T;
  games?: T;
  batInnings?: T;
  batNotOuts?: T;
  batRuns?: T;
  batHighScore?: T;
  batBalls?: T;
  batFours?: T;
  batSixes?: T;
  batRunsUnballed?: T;
  bowlBalls?: T;
  bowlMaidens?: T;
  bowlRuns?: T;
  bowlWickets?: T;
  bowlBestWickets?: T;
  bowlBestRuns?: T;
  catches?: T;
  batHighScoreNotOut?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-sync-runs_select".
 */
export interface PlayerSyncRunsSelect<T extends boolean = true> {
  startedAt?: T;
  finishedAt?: T;
  status?: T;
  playersCreated?: T;
  seasonRows?: T;
  matchesUpserted?: T;
  matchesSkipped?: T;
  matchMismatches?: T;
  matchError?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-sponsors_select".
 */
export interface PlayerSponsorsSelect<T extends boolean = true> {
  player?: T;
  sponsor?: T;
  season?: T;
  message?: T;
  featured?: T;
  sortOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "yearbooks_select".
 */
export interface YearbooksSelect<T extends boolean = true> {
  title?: T;
  seasonName?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  cover?: T;
  premiership?: T;
  presidentMessage?: T;
  coachMessage?: T;
  sponsorMessage?: T;
  photos?: T;
  featuredSponsors?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  showInNavigation?: T;
  navLabel?: T;
  navOrder?: T;
  content?:
    | T
    | {
        text?:
          | T
          | {
              richText?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              url?: T;
              style?: T;
              note?: T;
              id?: T;
              blockName?: T;
            };
      };
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  cover?: T;
  excerpt?: T;
  body?: T;
  author?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  gameId?: T;
  status?: T;
  type?: T;
  seasonName?: T;
  seasonStartYear?: T;
  competitionName?: T;
  gradeId?: T;
  gradeName?: T;
  roundName?: T;
  roundAbbr?: T;
  isFinalRound?: T;
  startsAt?: T;
  localDate?: T;
  days?: T;
  venueName?: T;
  venueSuburb?: T;
  clubTeamId?: T;
  clubTeamName?: T;
  opponentTeamId?: T;
  opponentName?: T;
  opponentOrgId?: T;
  opponentOrgName?: T;
  isHome?: T;
  tossWinnerTeamId?: T;
  tossChoice?: T;
  clubWonToss?: T;
  clubOutcome?: T;
  opponentOutcome?: T;
  result?: T;
  byForfeit?: T;
  onFirstInnings?: T;
  playhqUpdatedAt?: T;
  sourceHash?: T;
  syncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match-innings_select".
 */
export interface MatchInningsSelect<T extends boolean = true> {
  match?: T;
  sequenceNo?: T;
  periodName?: T;
  battingTeamId?: T;
  bowlingTeamId?: T;
  isClubBatting?: T;
  periodStatus?: T;
  played?: T;
  declared?: T;
  allOut?: T;
  totalRuns?: T;
  totalWickets?: T;
  totalBalls?: T;
  extrasTotal?: T;
  wides?: T;
  noBalls?: T;
  byes?: T;
  legByes?: T;
  penalty?: T;
  hasFallOfWickets?: T;
  hasBowlingData?: T;
  hasBallData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match-appearances_select".
 */
export interface MatchAppearancesSelect<T extends boolean = true> {
  match?: T;
  appearanceId?: T;
  teamId?: T;
  isClubSide?: T;
  player?: T;
  nameKey?: T;
  displayName?: T;
  captainRole?: T;
  isFillIn?: T;
  isRegisteredPlayer?: T;
  playerNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match-batting_select".
 */
export interface MatchBattingSelect<T extends boolean = true> {
  innings?: T;
  match?: T;
  appearanceId?: T;
  position?: T;
  battingStatus?: T;
  runs?: T;
  balls?: T;
  fours?: T;
  sixes?: T;
  dismissalType?: T;
  bowlerAppearanceId?: T;
  fielderAppearanceId?: T;
  fowWicket?: T;
  fowRuns?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match-bowling_select".
 */
export interface MatchBowlingSelect<T extends boolean = true> {
  innings?: T;
  match?: T;
  appearanceId?: T;
  order?: T;
  balls?: T;
  maidens?: T;
  runs?: T;
  wickets?: T;
  wides?: T;
  noBalls?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "match-fielding_select".
 */
export interface MatchFieldingSelect<T extends boolean = true> {
  innings?: T;
  match?: T;
  appearanceId?: T;
  catches?: T;
  keeperCatches?: T;
  stumpings?: T;
  runOutsAssisted?: T;
  runOutsUnassisted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Club name, contact details, social links and page titles for search engines.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "club".
 */
export interface Club {
  id: number;
  name: string;
  /**
   * Short form of the name, e.g. on the admin sign-in screen.
   */
  shortName?: string | null;
  /**
   * Shown under the club name, e.g. the home ground location.
   */
  tagline?: string | null;
  sport?: string | null;
  /**
   * Canonical site URL (no trailing slash). Drives canonical links, the sitemap and structured data. When the CANONICAL_HOST environment variable is set (always, in production) that host is used instead of this value.
   */
  siteUrl?: string | null;
  /**
   * Falls back to /assets/branding/logo.png.
   */
  logo?: (number | null) | Media;
  locale?: string | null;
  ogLocale?: string | null;
  email?: string | null;
  sponsorshipSubject?: string | null;
  address?: {
    locality?: string | null;
    region?: string | null;
    regionName?: string | null;
    country?: string | null;
    countryName?: string | null;
  };
  /**
   * Google Maps search for the contact page map.
   */
  mapQuery?: string | null;
  /**
   * An empty URL shows the label as plain text.
   */
  socials?:
    | {
        platform: 'facebook' | 'instagram' | 'x' | 'youtube' | 'tiktok';
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  defaultTitle?: string | null;
  titleSuffix?: string | null;
  defaultDescription?: string | null;
  /**
   * Falls back to /og-image.jpg (1200×630).
   */
  ogImage?: (number | null) | Media;
  ogImageAlt?: string | null;
  pages?: {
    home?: {
      title?: string | null;
      description?: string | null;
    };
    sponsors?: {
      title?: string | null;
      description?: string | null;
    };
    gallery?: {
      title?: string | null;
      description?: string | null;
    };
    documents?: {
      title?: string | null;
      description?: string | null;
    };
    contact?: {
      title?: string | null;
      description?: string | null;
    };
    people?: {
      title?: string | null;
      description?: string | null;
    };
    announcements?: {
      title?: string | null;
      description?: string | null;
    };
    history?: {
      title?: string | null;
      description?: string | null;
    };
    historySubmit?: {
      title?: string | null;
      description?: string | null;
    };
    events?: {
      title?: string | null;
      description?: string | null;
    };
    players?: {
      title?: string | null;
      description?: string | null;
    };
    fixtures?: {
      title?: string | null;
      description?: string | null;
    };
    stats?: {
      title?: string | null;
      description?: string | null;
    };
    records?: {
      title?: string | null;
      description?: string | null;
    };
    honours?: {
      title?: string | null;
      description?: string | null;
    };
    compare?: {
      title?: string | null;
      description?: string | null;
    };
    statlab?: {
      title?: string | null;
      description?: string | null;
    };
    yearbooks?: {
      title?: string | null;
      description?: string | null;
    };
    matches?: {
      title?: string | null;
      description?: string | null;
    };
    news?: {
      title?: string | null;
      description?: string | null;
    };
  };
  history?: {
    /**
     * Separate paragraphs with a blank line.
     */
    narrative?: string | null;
    pullQuote?: string | null;
    callout?: {
      eyebrow?: string | null;
      title?: string | null;
      body?: string | null;
    };
  };
  storySubmitIntro?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The link to buy club clothing. Shown as a gold button in the menu, on the home page and in the footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "club-apparel".
 */
export interface ClubApparel {
  id: number;
  /**
   * Paste the full web address of the shop, starting with https://. Leave empty to hide the apparel button everywhere on the website.
   */
  apparelUrl?: string | null;
  /**
   * The words on the button. If you leave it empty it says "Club apparel".
   */
  apparelLabel?: string | null;
  /**
   * A sentence to sit beside the button on the home page, for example "Order your playing shirt and club hoodie online."
   */
  apparelBlurb?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Sponsors in these tiers scroll across the home page under the hero. Leave empty to hide the carousel.
   */
  sponsorCarouselTiers?: ('Platinum' | 'Gold' | 'Silver' | 'Bronze' | 'Player')[] | null;
  stats?: {
    /**
     * Visitors can add juniors with the toggle. Categories with no data are not offered.
     */
    defaultIncludedCategories?: ('senior' | 'junior' | 'womens' | 'masters' | 'mixed')[] | null;
    /**
     * Extra patterns that decide a grade category. They are tried before the built-in rules, in order.
     */
    gradeRules?:
      | {
          category: 'senior' | 'junior' | 'womens' | 'masters' | 'mixed';
          /**
           * A regular expression tested against the grade name, then the team name.
           */
          pattern: string;
          flags?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Players below a minimum are listed under "Not enough data yet" and never ranked.
     */
    qualification?: {
      career?: {
        batAvgRuns?: number | null;
        batAvgInnings?: number | null;
        srBalls?: number | null;
        bowlAvgWickets?: number | null;
        econBalls?: number | null;
      };
      season?: {
        batAvgRuns?: number | null;
        batAvgInnings?: number | null;
        srBalls?: number | null;
        bowlAvgWickets?: number | null;
        econBalls?: number | null;
      };
    };
    /**
     * How much match data a rate needs before it is shown (otherwise the page shows the counts and a dash). Used by the match analysis on profiles, opposition and leaderboards.
     */
    matchMinimums?: {
      oppositionInnings?: number | null;
      oppositionBalls?: number | null;
      positionInnings?: number | null;
      rateInnings?: number | null;
      winGames?: number | null;
      ballsForBoundary?: number | null;
      partnershipPairGames?: number | null;
    };
    milestoneThresholds?: {
      games?: number[] | null;
      runs?: number[] | null;
      wickets?: number[] | null;
      catches?: number[] | null;
    };
    approachWindow?: {
      games?: number | null;
      runs?: number | null;
      wickets?: number | null;
      catches?: number | null;
    };
    /**
     * Groups on the honour board. An honour is placed in the first category whose keyword it contains; anything else is "Other". Leave empty for the defaults.
     */
    honourCategories?:
      | {
          label: string;
          keywords: string[];
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The colours, crest and heading font of the whole website and this admin. Saving changes the live site within seconds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  /**
   * The five colours a designer chooses. Type a hex code as a # followed by six hex digits.
   */
  palette: {
    /**
     * Dark backgrounds, headings and dark buttons.
     */
    primary: string;
    /**
     * Buttons, the current menu item, the keyboard focus ring and highlighted text.
     */
    accent: string;
    /**
     * The alternate light band between page sections.
     */
    surface: string;
    /**
     * Normal reading text on light backgrounds.
     */
    text: string;
    /**
     * Introductions and less important text.
     */
    muted: string;
  };
  /**
   * Supporting shades. Leave them alone unless you changed the accent or dark colour; each one is edited directly.
   */
  shades: {
    /**
     * A slightly lighter dark for menus and badges on the dark colour.
     */
    ink: string;
    /**
     * The start of the thin gradient line under headings.
     */
    accentDark: string;
    /**
     * Button hover and labels on dark backgrounds.
     */
    accentLight: string;
    /**
     * Tinted chips, callouts and date tiles.
     */
    accentPale: string;
    /**
     * Small accent-coloured text on light backgrounds. Must be dark enough to read.
     */
    accentDeep: string;
    /**
     * Card backgrounds and empty states.
     */
    surfaceMuted: string;
    /**
     * Captions and placeholders.
     */
    mutedLight: string;
  };
  /**
   * A PNG (or JPEG; no SVG or WebP) with a transparent background, at least 512 pixels tall. It is shown on a white tile in the menu, footer and admin sign-in, and on the stat cards. If empty, the logo in Club details is used, then the bundled crest.
   */
  crest?: (number | null) | Media;
  /**
   * The display face for headings, numbers and the stat cards. The body text stays Inter.
   */
  headingFont: 'barlow-condensed' | 'oswald' | 'bebas-neue' | 'anton' | 'playfair-display';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "club_select".
 */
export interface ClubSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  tagline?: T;
  sport?: T;
  siteUrl?: T;
  logo?: T;
  locale?: T;
  ogLocale?: T;
  email?: T;
  sponsorshipSubject?: T;
  address?:
    | T
    | {
        locality?: T;
        region?: T;
        regionName?: T;
        country?: T;
        countryName?: T;
      };
  mapQuery?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  defaultTitle?: T;
  titleSuffix?: T;
  defaultDescription?: T;
  ogImage?: T;
  ogImageAlt?: T;
  pages?:
    | T
    | {
        home?:
          | T
          | {
              title?: T;
              description?: T;
            };
        sponsors?:
          | T
          | {
              title?: T;
              description?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              description?: T;
            };
        documents?:
          | T
          | {
              title?: T;
              description?: T;
            };
        contact?:
          | T
          | {
              title?: T;
              description?: T;
            };
        people?:
          | T
          | {
              title?: T;
              description?: T;
            };
        announcements?:
          | T
          | {
              title?: T;
              description?: T;
            };
        history?:
          | T
          | {
              title?: T;
              description?: T;
            };
        historySubmit?:
          | T
          | {
              title?: T;
              description?: T;
            };
        events?:
          | T
          | {
              title?: T;
              description?: T;
            };
        players?:
          | T
          | {
              title?: T;
              description?: T;
            };
        fixtures?:
          | T
          | {
              title?: T;
              description?: T;
            };
        stats?:
          | T
          | {
              title?: T;
              description?: T;
            };
        records?:
          | T
          | {
              title?: T;
              description?: T;
            };
        honours?:
          | T
          | {
              title?: T;
              description?: T;
            };
        compare?:
          | T
          | {
              title?: T;
              description?: T;
            };
        statlab?:
          | T
          | {
              title?: T;
              description?: T;
            };
        yearbooks?:
          | T
          | {
              title?: T;
              description?: T;
            };
        matches?:
          | T
          | {
              title?: T;
              description?: T;
            };
        news?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  history?:
    | T
    | {
        narrative?: T;
        pullQuote?: T;
        callout?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
            };
      };
  storySubmitIntro?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "club-apparel_select".
 */
export interface ClubApparelSelect<T extends boolean = true> {
  apparelUrl?: T;
  apparelLabel?: T;
  apparelBlurb?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  sponsorCarouselTiers?: T;
  stats?:
    | T
    | {
        defaultIncludedCategories?: T;
        gradeRules?:
          | T
          | {
              category?: T;
              pattern?: T;
              flags?: T;
              id?: T;
            };
        qualification?:
          | T
          | {
              career?:
                | T
                | {
                    batAvgRuns?: T;
                    batAvgInnings?: T;
                    srBalls?: T;
                    bowlAvgWickets?: T;
                    econBalls?: T;
                  };
              season?:
                | T
                | {
                    batAvgRuns?: T;
                    batAvgInnings?: T;
                    srBalls?: T;
                    bowlAvgWickets?: T;
                    econBalls?: T;
                  };
            };
        matchMinimums?:
          | T
          | {
              oppositionInnings?: T;
              oppositionBalls?: T;
              positionInnings?: T;
              rateInnings?: T;
              winGames?: T;
              ballsForBoundary?: T;
              partnershipPairGames?: T;
            };
        milestoneThresholds?:
          | T
          | {
              games?: T;
              runs?: T;
              wickets?: T;
              catches?: T;
            };
        approachWindow?:
          | T
          | {
              games?: T;
              runs?: T;
              wickets?: T;
              catches?: T;
            };
        honourCategories?:
          | T
          | {
              label?: T;
              keywords?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  palette?:
    | T
    | {
        primary?: T;
        accent?: T;
        surface?: T;
        text?: T;
        muted?: T;
      };
  shades?:
    | T
    | {
        ink?: T;
        accentDark?: T;
        accentLight?: T;
        accentPale?: T;
        accentDeep?: T;
        surfaceMuted?: T;
        mutedLight?: T;
      };
  crest?: T;
  headingFont?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}