/* Generated by Payload at first, then customised: the theme variables are rendered before the admin
   (see lib/theme.ts). Payload tooling does not rewrite this file in this project. */
import config from '@payload-config'
import '@payloadcms/next/css'
import type { ServerFunctionClient } from 'payload'
import { handleServerFunctions, RootLayout } from '@payloadcms/next/layouts'
import React from 'react'

import { ThemeStyle } from '@/components/theme-style'
import { getTheme } from '@/lib/theme'
import { importMap } from './admin/importMap.js'
import './custom.scss'

type Args = {
  children: React.ReactNode
}

const serverFunction: ServerFunctionClient = async function (args) {
  'use server'
  return handleServerFunctions({
    ...args,
    config,
    importMap,
  })
}

const Layout = async ({ children }: Args) => {
  const theme = await getTheme()
  return (
    <RootLayout config={config} importMap={importMap} serverFunction={serverFunction}>
      {/* Sibling before the admin: RootLayout puts its children in <body>; the <style> applies document-wide. */}
      <ThemeStyle theme={theme} />
      {children}
    </RootLayout>
  )
}

export default Layout
