/* Generated by Payload at first, then customised: the theme variables are set on <html> before the admin
   (see lib/theme.ts). Payload tooling does not rewrite this file in this project. */
import config from '@payload-config'
import '@payloadcms/next/css'
import type { ServerFunctionClient } from 'payload'
import { handleServerFunctions, RootLayout } from '@payloadcms/next/layouts'
import React from 'react'

import { themeCssVars } from '@/lib/theme/css'
import { getTheme } from '@/lib/theme'
import { importMap } from './admin/importMap.js'
import './custom.scss'

type Args = {
  children: React.ReactNode
}

const serverFunction: ServerFunctionClient = async function (args) {
  'use server'
  return handleServerFunctions({
    ...args,
    config,
    importMap,
  })
}

const Layout = async ({ children }: Args) => {
  const theme = await getTheme()
  return (
    <RootLayout
      config={config}
      importMap={importMap}
      serverFunction={serverFunction}
      // The --brand-* variables go on <html> itself: RootLayout owns <head> and the admin body streams in,
      // so an inline style attribute is the one place guaranteed to be in the first HTML.
      htmlProps={{ style: themeCssVars(theme) as React.CSSProperties }}
    >
      {children}
    </RootLayout>
  )
}

export default Layout
